wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.22
    framework: huggingface
    huggingface_version: 4.4.2
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.7.10
    t:
      1:
      - 1
      - 9
      - 11
      4: 3.7.10
      5: 0.10.22
      6: 4.4.2
      8:
      - 1
      - 5
